version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.4-buster
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo apt-get update && sudo apt-get install -y g++ cmake libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
      - run:
          name: Run CMake
          command: cmake .
      - run:
          name: Build
          command: make