name: benchmark

on: pull_request

jobs:
  benchmark:
    name: Benchmark performance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout head
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build chess engine
        run: gcc src/fast-chess.c -o bin/fast-chess -I include/

      - name: Solve Morphy mate in 2
        run: ./bin/fast-chess -f "kbK5/pp6/1P6/8/8/8/8/R7 w - - 0 1"
